(
cd enso/;
make FW=360;
make FW=365;
cd ../patches/loader/;
make;
cd ../hencfg/;
make;
cd ../culogo/;
make;
cd ../recovery/;
make;
cd ../../installer/;
cmake ./ && make;
mv enso_installer.vpk ../enso_ex.vpk;
rm -rf CMakeFiles && rm cmake_install.cmake && rm CMakeCache.txt && rm Makefile;
rm -rf emmc_* && rm enso_* && rm kernel2* && rm version.h && rm libemmc*;
cd ../patches/hencfg/;
rm e2xhencfg.*;
rm kernel.o;
cd ../culogo/;
rm e2xculogo.*;
rm kernel.o;
cd ../loader/;
rm e2x_ckldr.*;
rm kernel.o;
cd ../recovery/;
rm eex_recovery.*;
rm kernel.o;
cd ../../enso/;
rm *.bin;
echo "";
echo "DONE! [ enso_ex.vpk ]";
echo "";
)