(
cd enso/;
make;
echo "#define FATCHECK 0x$(crc32 fat.bin)" > ../installer/src/fatcheck.h;
cd ../recovery/blob/;
make;
cd ../;
make;
cd ../patches/loader/;
make;
cd ../hencfg/;
make;
cd ../culogo/;
make;
cd ../../installer/;
cmake ./ && make;
mv enso_installer.vpk ../enso_ex.vpk;
rm -rf CMakeFiles && rm cmake_install.cmake && rm CMakeCache.txt && rm Makefile;
rm -rf emmc_* && rm enso_* && rm kernel2* && rm version.h && rm libemmc*;
cd ../patches/hencfg/;
rm e2xhencfg.*;
rm kernel.o;
cd ../culogo/;
rm e2xculogo.*;
rm kernel.o;
cd ../loader/;
rm e2x_ckldr.*;
rm kernel.o;
cd ../../enso/;
rm *.bin;
cd ../recovery/;
rm *.elf && rm *.o && rm *.e2xp;
cd blob/;
rm *.elf && rm *.o && rm *.e2xp;
echo "";
echo "DONE! [ enso_ex.vpk ]";
echo "";
)